# Generated by Django 5.2.4 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.CharField(default='Emloyee', max_length=15),
        ),
    ]
