# Generated by Django 5.2.4 on 2025-07-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_name_item_firstname_item_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.CharField(choices=[('tl', 'Tl'), ('sd1', 'Sd1'), ('sd2', 'Sd2'), ('sd3', 'Sd3'), ('sd4', 'Sd4')], default='sd1', max_length=15),
        ),
    ]
